r"""
NX drawing generator — ASME-compliant engineering drawing from a part file.

Runs inside NX via run_journal.exe (headless). Produces a master-model drawing
part (<model>_dwg.prt), a PDF, and a dimension coverage report next to the model.

Usage:  set NXDRAW_MODEL=C:\path\to\model.prt
        "<NX>\NXBIN\run_journal.exe" nx_drawing_generator.py

Pipeline (each stage feeds the next):
  1. analyze   — geometry facts: planar coordinate levels per axis, circles
                 (center/axis/radius), planar-face areas, edge inventory
  2. plan      — every dimension + GD&T control the part needs, assigned to
                 view sides before layout
  3. field     — drawable area + obstacles detected from the template's own
                 curves and annotations (border, title block, notes, symbols)
  4. layout    — scale + view positions solved with reserved bands for the
                 planned dimension rows; iso placed by overlap testing
  5. render    — views, then dimensions/GD&T stacked outward
  6. report    — coverage: what was dimensioned, what was not and why

Standards map — where each rule comes from:

  ASME Y14.1 / Y14.1M (sheet sizes & format)
    - Inch sheets A-F, metric A0-A4; borders, zone grid, title block come from
      the Siemens drawing templates (TEMPLATE_KEEPOUTS marks their regions).
  ASME Y14.3 (orthographic & pictorial views)
    - Third-angle projection: Top view directly above Front, Right view to the
      right of Front, both aligned (solve_layout keeps shared coordinates).
    - Projection symbol on the sheet comes from the template.
    - Pictorial (isometric) view added for clarity; hidden lines omitted in it.
  ASME Y14.2 (line conventions)
    - Hidden lines rendered dashed in orthographic views (view style);
      centerlines generated by NX per the drafting standard.
  ASME Y14.5 (dimensioning & tolerancing; 2009 section refs)
    - para 1.7.1 spacing: first dim line ~10mm from the view, successive rows
      ~6mm min; here 12mm/8mm (reserves(), dim_origin()).
    - Longer dims placed outside shorter ones (row assignment by span) so
      extension lines do not cross dimension lines.
    - Dimension text centered between its arrowheads (dim_origin mid-span).
    - Rectangular-coordinate/baseline dimensioning from the datum planes
      (plan_dimensions: every level dimensioned from the DRF face per axis).
    - Each feature of size fully located from the DRF; equal-value locations
      on different features are still separate dimensions.
    - Hole callouts: diameter symbol via NX hole-style radial dim; "THRU" /
      "<depth> DEEP" appended (words per pre-1994 practice, still allowed).
    - Locations controlled by position tolerances are BASIC dims (para 8.4);
      set via Dimension.ToleranceType.Basic.
    - Datum reference frame (section 4): 3-2-1 scheme — primary datum A =
      largest planar face (seating), B = largest face perpendicular to A,
      C = the remaining direction (pick_datums()).
    - Datum feature qualification: form tolerance (flatness) on the primary
      datum face; orientation (perpendicularity |A, |A|B) on secondary and
      tertiary — frames stacked with their datum feature symbols.
    - Position FCF per hole (section 10): primary datum = the plane
      perpendicular to the hole axis (controls axis squareness), remaining
      datums in precedence order; diameter zone symbol on the tolerance.
    - FCF association: frame grouped directly below the size callout reads as
      applying to that feature of size (para 6.4 placement practice).
    - Leaders must not cross dimension lines; crossing extension lines is
      permitted when unavoidable (datum corner-escape logic in render).
    - General tolerance note ("UNLESS OTHERWISE SPECIFIED ...") covers all
      dims without direct tolerances (para 4.1 / title-block practice).
  Scale selection
    - Preferred ratios only (1:1, 1:2, 1:4, 1:5 ... 2:1, 5:1 ...), largest
      that fits the sheet with all reserved annotation bands (STD_SCALES).

  Default tolerance VALUES (GDT dict) are engineering-plausible placeholders;
  real values are design intent and should come from user configuration.
"""

import math
import os
import traceback

import NXOpen
import NXOpen.Annotations
import NXOpen.Drawings
import NXOpen.Preferences

MODEL = os.environ.get("NXDRAW_MODEL", "")
if not MODEL:
    raise RuntimeError("Set NXDRAW_MODEL to the part file path "
                       "(or run via generate_drawing.cmd)")
OUT_BASE = os.path.splitext(MODEL)[0] + "_dwg"
DWG = OUT_BASE + ".prt"
PDF = OUT_BASE + ".pdf"
REPORT = OUT_BASE + "_report.txt"

# Preferred scale ratios only (drawing practice / ISO 5455); the solver takes
# the largest that fits — intermediate ratios like 3:4 are not used.
STD_SCALES = [(10, 1), (5, 1), (4, 1), (2, 1), (1, 1),
              (1, 2), (1, 4), (1, 5), (1, 10), (1, 20), (1, 50)]

# Default tolerance scheme (design intent would override these; values are
# ASME-plausible defaults so every drawing carries a complete DRF + controls)
GDT = {
    True:  {"pos": "0.25", "flat": "0.1",
            "note": ["UNLESS OTHERWISE SPECIFIED:",
                     "ALL LINEAR DIMENSIONS \xb10.5",
                     "ALL ANGULAR DIMENSIONS \xb10.5 DEG"]},   # metric (mm)
    False: {"pos": "0.010", "flat": "0.004",
            "note": ["UNLESS OTHERWISE SPECIFIED:",
                     "ALL LINEAR DIMENSIONS \xb1.02",
                     "ALL ANGULAR DIMENSIONS \xb10.5 DEG"]},   # inch
}

# Per-template keep-out regions (sheet coords, drawing-part units): title block,
# disclaimer text, projection symbol, units note. These are drawn by the template
# as title-block/symbol objects that are not discoverable as ordinary curves or
# notes, so each supported template declares its reserved regions here.
TEMPLATE_KEEPOUTS = {
    "Drawing-A3-Size-template.prt": [(243.0, 10.0, 407.0, 103.0),
                                     (138.0, 8.0, 245.0, 48.0)],
    "Drawing-B-Size-template.prt": [(9.9, 0.35, 16.65, 3.6),
                                    (5.4, 0.3, 9.95, 1.85)],
}

s = NXOpen.Session.GetSession()
lw = s.ListingWindow
lw.Open()
say = lw.WriteLine
report_lines = []


def rep(msg):
    say(msg)
    report_lines.append(msg)


def cluster(vals, tol):
    """Sorted distinct values, merging values closer than tol."""
    out = []
    for v in sorted(vals):
        if not out or v - out[-1][-1] > tol:
            out.append([v])
        else:
            out[-1].append(v)
    return [sum(g) / len(g) for g in out]


class Rect(object):
    def __init__(self, x0, y0, x1, y1):
        self.x0, self.y0, self.x1, self.y1 = min(x0, x1), min(y0, y1), max(x0, x1), max(y0, y1)

    def overlaps(self, o, pad=0.0):
        return not (self.x1 + pad < o.x0 or o.x1 + pad < self.x0 or
                    self.y1 + pad < o.y0 or o.y1 + pad < self.y0)

    def union(self, o):
        return Rect(min(self.x0, o.x0), min(self.y0, o.y0),
                    max(self.x1, o.x1), max(self.y1, o.y1))

    def __repr__(self):
        return "Rect(%.1f,%.1f - %.1f,%.1f)" % (self.x0, self.y0, self.x1, self.y1)


# ---------------------------------------------------------------- 1. analyze
def model_bodies(master):
    """Bodies the drawing views actually display: the solids-only reference
    set if one exists (tool/construction bodies live outside it)."""
    try:
        for rs in master.GetAllReferenceSets():
            if rs.Name.upper() not in ("MODEL", "SOLID", "BODY"):
                continue
            for getter in ("AskAllDirectMembers", "GetAllDirectMembers",
                           "AskMembersInReferenceSet", "GetMembers"):
                if hasattr(rs, getter):
                    try:
                        members = getattr(rs, getter)()
                        bodies = [m for m in members if isinstance(m, NXOpen.Body)]
                        if bodies:
                            say("Analyzing %d body(ies) from refset %s"
                                % (len(bodies), rs.Name))
                            return bodies
                    except Exception:
                        continue
    except Exception:
        pass
    bodies = [b for b in master.Bodies]
    if len(bodies) > 1:
        rep("WARNING: %d bodies, no solids refset — analyzing all (tool "
            "remnants may pollute the dimension scheme)" % len(bodies))
    return bodies


class Geometry(object):
    def __init__(self, master):
        self.lo = [1e30] * 3
        self.hi = [-1e30] * 3
        self.lin_edges = []      # (edge, pa, pb, unit_dir)
        self.circles = []        # dict: edge, center(3), axis(int 0/1/2), r
        verts = [[], [], []]
        self.bodies = model_bodies(master)
        for b in self.bodies:
            for e in b.GetEdges():
                try:
                    vs = e.GetVertices()
                except Exception:
                    vs = []
                for p in vs:
                    for i, c in enumerate((p.X, p.Y, p.Z)):
                        self.lo[i] = min(self.lo[i], c)
                        self.hi[i] = max(self.hi[i], c)
                try:
                    et = e.SolidEdgeType
                except Exception:
                    continue
                if et == NXOpen.Edge.EdgeType.Linear and len(vs) == 2:
                    a, b2 = vs
                    d = [b2.X - a.X, b2.Y - a.Y, b2.Z - a.Z]
                    ln = math.sqrt(sum(c * c for c in d))
                    if ln > 1e-9:
                        self.lin_edges.append((e, a, b2, [c / ln for c in d]))
                        # coordinate levels only from linear-edge endpoints
                        # (circle seam vertices are parametric noise)
                        for p in vs:
                            for i, c in enumerate((p.X, p.Y, p.Z)):
                                verts[i].append(c)
                elif et == NXOpen.Edge.EdgeType.Circular:
                    self.n_circ = getattr(self, "n_circ", 0) + 1
                    try:
                        c = self._fit_circle(e)
                    except Exception:
                        say("circle fit raised on edge %d:\n%s"
                            % (e.Tag, traceback.format_exc().splitlines()[-1]))
                        c = None
                    if c:
                        self.circles.append(c)
                    else:
                        self.n_circ_fail = getattr(self, "n_circ_fail", 0) + 1
        for c in self.circles:
            for i in range(3):
                self.lo[i] = min(self.lo[i], c["center"][i] - (c["r"] if i != c["axis"] else 0))
                self.hi[i] = max(self.hi[i], c["center"][i] + (c["r"] if i != c["axis"] else 0))
        self.ext = [self.hi[i] - self.lo[i] for i in range(3)]
        tol = max(self.ext) * 1e-3 + 1e-6
        self.levels = [cluster(verts[i], tol) for i in range(3)]
        # planar faces (axis-aligned): (axis, coord, approx_area) for datum choice
        self.planar_faces = []
        for b in self.bodies:
            for f in b.GetFaces():
                try:
                    if f.SolidFaceType != NXOpen.Face.FaceType.Planar:
                        continue
                    pts = []
                    for e in f.GetEdges():
                        try:
                            pts.extend(e.GetVertices())
                        except Exception:
                            pass
                    if len(pts) < 3:
                        continue
                    for axis in range(3):
                        cs = [(p.X, p.Y, p.Z)[axis] for p in pts]
                        if max(cs) - min(cs) < tol:
                            o1, o2 = [i for i in range(3) if i != axis]
                            e1 = [(p.X, p.Y, p.Z)[o1] for p in pts]
                            e2 = [(p.X, p.Y, p.Z)[o2] for p in pts]
                            area = (max(e1) - min(e1)) * (max(e2) - min(e2))
                            if area > tol * tol:
                                self.planar_faces.append(
                                    (axis, sum(cs) / len(cs), area))
                            break
                except Exception:
                    pass

    def _fit_circle(self, e):
        """Fit center/axis/radius from points on the circular edge."""
        pts = None
        try:
            pts = e.GetLocations()
        except Exception:
            pass
        if not pts or len(pts) < 3:
            return None
        def xyz(p):
            for attr in ("X", None):
                if attr and hasattr(p, "X"):
                    return (p.X, p.Y, p.Z)
            for attr in ("Point", "Location", "Position"):
                q = getattr(p, attr, None)
                if q is not None and hasattr(q, "X"):
                    return (q.X, q.Y, q.Z)
            raise AttributeError("no point in %s: %s" % (type(p), dir(p)))
        # CurveLocation.Type: 2 = center, others are on-curve points
        center = None
        rim = []
        for p in pts:
            q = xyz(p)
            t = getattr(p, "Type", None)
            try:
                is_center = int(str(t)) == 2
            except Exception:
                is_center = "2" in str(t) or "enter" in str(t)
            if is_center:
                center = q
            else:
                rim.append(q)
        if center is None or len(rim) < 2:
            return None
        radials = [[q[i] - center[i] for i in range(3)] for q in rim]
        # axis = normal of rim plane: largest cross product of radius vectors
        best_n, best_ln = None, 0.0
        for i in range(len(radials)):
            for j in range(i + 1, len(radials)):
                v1, v2 = radials[i], radials[j]
                n = [v1[1] * v2[2] - v1[2] * v2[1],
                     v1[2] * v2[0] - v1[0] * v2[2],
                     v1[0] * v2[1] - v1[1] * v2[0]]
                ln = math.sqrt(sum(c * c for c in n))
                if ln > best_ln:
                    best_n, best_ln = n, ln
        if best_ln < 1e-12:
            return None
        n = [abs(c / best_ln) for c in best_n]
        axis = n.index(max(n))
        if n[axis] < 0.99:
            return None            # not axis-aligned; reported as uncovered later
        r = sum(math.sqrt(sum(v * v for v in rv)) for rv in radials) / len(radials)
        return {"edge": e, "center": list(center), "axis": axis, "r": r}


def group_holes(geom):
    """Group coaxial circles into hole/boss features."""
    groups = {}
    for c in geom.circles:
        ax = c["axis"]
        o1, o2 = [i for i in range(3) if i != ax]
        key = (ax, round(c["center"][o1], 2), round(c["center"][o2], 2), round(c["r"], 2))
        groups.setdefault(key, []).append(c)
    holes = []
    for (ax, k1, k2, r), cs in sorted(groups.items()):
        zs = [c["center"][ax] for c in cs]
        span = max(zs) - min(zs) if len(cs) > 1 else 0.0
        through = span >= geom.ext[ax] - max(geom.ext) * 1e-3
        holes.append({"axis": ax, "center": cs[0]["center"], "r": r,
                      "span": span, "through": through,
                      "edge": max(cs, key=lambda c: c["center"][ax])["edge"]})
    return holes


# ------------------------------------------------------------------- 2. plan
# Third-angle multiview set per ASME Y14.3: Front is the principal view,
# Top directly above it, Right directly beside it, projection-aligned.
# view definitions: name -> (h_axis, v_axis, normal_axis) in model space
VIEWDEF = {"Front": (0, 2, 1), "Top": (0, 1, 2), "Right": (1, 2, 0)}
# A hole is dimensioned in the view where it appears true-shape (circle),
# i.e. the view whose normal parallels the hole axis (Y14.5: contour rule —
# features dimensioned where their shape is shown).
HOLE_VIEW = {2: "Top", 1: "Front", 0: "Right"}


class DimSpec(object):
    def __init__(self, kind, view_name, axis, label, **kw):
        self.kind = kind          # linear | dia | pos
        self.view_name = view_name
        self.axis = axis
        self.label = label
        self.side = None          # below/left/right/above
        self.row = 0
        self.span = 0.0
        self.__dict__.update(kw)
        self.ok = False
        self.why = ""


def edge_at(geom, coord, meas_axis, dir_axis, tol):
    """Linear edge parallel to dir_axis whose midpoint sits at coord on meas_axis."""
    for e, a, b, d in geom.lin_edges:
        if abs(d[dir_axis]) < 0.99:
            continue
        mid = [(a.X + b.X) / 2, (a.Y + b.Y) / 2, (a.Z + b.Z) / 2]
        if abs(mid[meas_axis] - coord) <= tol:
            return e, NXOpen.Point3d(mid[0], mid[1], mid[2])
    return None, None


def pick_datums(geom):
    """Datum reference frame per ASME Y14.5 section 4 (3-2-1 principle):
    the primary datum constrains 3 DOF and should be the functional seating
    surface — absent design intent, the largest planar face; secondary (2 DOF)
    the largest face perpendicular to it; tertiary (1 DOF) the remaining
    direction. Coplanar faces are aggregated by area; ties break to the lower
    coordinate for determinism. Returns {letter: (axis, coord)}."""
    tol = max(geom.ext) * 1e-3 + 1e-6
    plane_area = {}
    for axis, coord, area in geom.planar_faces:
        key = (axis, round(coord / (tol * 10)))
        cur = plane_area.get(key)
        plane_area[key] = (plane_area.get(key, (0.0, coord))[0] + area, coord)
    best_per_axis = {}
    for (axis, _), (area, coord) in plane_area.items():
        cur = best_per_axis.get(axis)
        # tie-break toward the lower coordinate (deterministic)
        if cur is None or area > cur[0] + tol or \
                (abs(area - cur[0]) <= tol and coord < cur[1]):
            best_per_axis[axis] = (area, coord)
    ranked = sorted(best_per_axis.items(), key=lambda kv: -kv[1][0])
    scheme = {}
    for letter, (axis, (area, coord)) in zip("ABC", ranked):
        scheme[letter] = (axis, coord)
    return scheme


def plan_dimensions(geom, holes, metric=True):
    tol = max(geom.ext) * 1e-3 + 1e-6
    specs = []
    tolset = GDT[metric]

    # --- datum reference frame drives everything: dims baseline from the
    # datum faces, hole locations are measured from them, FCFs reference them
    scheme = pick_datums(geom)
    datum_axis_letter = {axis: letter for letter, (axis, _) in scheme.items()}
    datum_coord = {axis: coord for _, (axis, coord) in scheme.items()}
    for axis in range(3):
        if axis not in datum_coord:
            datum_coord[axis] = geom.levels[axis][0] if geom.levels[axis] else 0.0
    for letter, (axis, coord) in sorted(scheme.items()):
        specs.append(DimSpec("scheme", "-", axis,
                             "DRF %s = %s plane @ %.5g" % (letter, "XYZ"[axis], coord),
                             skip=True, why="informational"))

    hole_coords = {0: set(), 1: set(), 2: set()}
    for h in holes:
        for i in range(3):
            if i != h["axis"]:
                hole_coords[i].add(round(h["center"][i], 3))

    # --- linear coverage: rectangular-coordinate (baseline) dimensioning per
    # ASME Y14.5 — every coordinate level measured from the DRF datum plane
    # of its axis, so linear dims and position tolerances share one origin
    AXIS_PLAN = {0: ("Front", True, "below"),
                 2: ("Front", False, "left"),
                 1: ("Top", False, "left")}
    for axis, (vname, horiz, side) in AXIS_PLAN.items():
        levels = geom.levels[axis]
        if len(levels) < 2:
            continue
        datum = datum_coord[axis]
        h_ax, v_ax, _ = VIEWDEF[vname]
        dir_axis = v_ax if horiz else h_ax
        e0, p0 = edge_at(geom, datum, axis, dir_axis, tol)
        for c in levels:
            if abs(c - datum) <= tol:
                continue
            label = "%s %.5g-%.5g" % ("XYZ"[axis], datum, c)
            sp = DimSpec("linear", vname, axis, label, horizontal=horiz)
            sp.side = side
            sp.span = abs(c - datum)
            # a real face level gets its own dim even if a hole center happens
            # to share the coordinate; only pure hole-center levels defer to
            # the hole position dim
            e1, p1 = edge_at(geom, c, axis, dir_axis, tol)
            if e0 and e1:
                sp.skip = False
                sp.geo = (e0, p0, e1, p1)
            elif any(abs(c - hc) < 0.01 for hc in hole_coords[axis]):
                sp.skip = True
                sp.why = "covered by hole position dim"
            else:
                sp.skip = True
                sp.why = "no supporting edge in %s view" % vname
            specs.append(sp)

    # --- holes: diameter callout (+ depth note if blind) + basic location
    # dims from the datum planes, in the true-shape view
    for h in holes:
        vname = HOLE_VIEW[h["axis"]]
        h_ax, v_ax, _ = VIEWDEF[vname]
        label = "dia %.5g%s" % (2 * h["r"],
                                "" if h["through"] else " x %.5g deep" % h["span"])
        specs.append(DimSpec("dia", vname, h["axis"], label, hole=h, skip=False,
                             side="callout"))
        # horizontal locations go below (between views) — the above corridor
        # is reserved for the diameter callout leaders
        for meas_axis, side, horiz in ((h_ax, "below", True), (v_ax, "right", False)):
            datum = datum_coord[meas_axis]
            dir_axis = v_ax if horiz else h_ax
            e0, p0 = edge_at(geom, datum, meas_axis, dir_axis, tol)
            sp = DimSpec("pos", vname, meas_axis,
                         "hole pos %s=%.5g" % ("XYZ"[meas_axis], h["center"][meas_axis]),
                         hole=h, horizontal=horiz)
            sp.side = side
            sp.span = abs(h["center"][meas_axis] - datum)
            if e0 is None:
                sp.skip = True
                sp.why = "no datum edge"
            else:
                sp.skip = False
                sp.geo = (e0, p0)
            specs.append(sp)

    # --- GD&T: datum feature symbols on the actual datum faces; the emptiest
    # candidate band wins so leaders cross nothing
    callout_views = set(HOLE_VIEW[h["axis"]] for h in holes)
    occ_count = {}
    for sp in specs:
        if sp.kind in ("linear", "pos") and not sp.skip:
            k = (sp.view_name, sp.side)
            occ_count[k] = occ_count.get(k, 0) + 1
    for v in callout_views:
        # the above corridor of callout views is reserved for leaders
        occ_count[(v, "above")] = occ_count.get((v, "above"), 0) + 5
    # sheet width is scarcer than height (title block owns the lower right):
    # nudge datum symbols toward below/above bands
    for vname in VIEWDEF:
        for side in ("left", "right"):
            occ_count[(vname, side)] = occ_count.get((vname, side), 0) + 1

    def datum_cands(axis, coord):
        is_max = geom.levels[axis] and \
            abs(coord - geom.levels[axis][-1]) < tol
        out = []
        for vname, (h_ax, v_ax, _) in VIEWDEF.items():
            if axis == v_ax:
                out.append((vname, "above" if is_max else "below"))
            elif axis == h_ax:
                out.append((vname, "right" if is_max else "left"))
        return out

    datum_ok = set()
    for letter, (axis, coord) in sorted(scheme.items()):
        placed = False
        cands = datum_cands(axis, coord)
        for vname, side in sorted(cands, key=lambda c: occ_count.get(c, 0)):
            h_ax, v_ax, _ = VIEWDEF[vname]
            dir_axis = h_ax if side in ("below", "above") else v_ax
            e, pt = edge_at(geom, coord, axis, dir_axis, tol)
            if e is None:
                continue
            sp = DimSpec("datum", vname, axis, "datum %s (%s=%.5g)"
                         % (letter, "XYZ"[axis], coord), letter=letter)
            sp.side = side
            sp.span = 1e9        # outermost row of its band
            sp.skip = False
            sp.geo = (e, pt)
            specs.append(sp)
            datum_ok.add(letter)
            occ_count[(vname, side)] = occ_count.get((vname, side), 0) + 1
            placed = True
            break
        if not placed:
            sp = DimSpec("datum", cands[0][0] if cands else "Front", axis,
                         "datum %s (%s=%.5g)" % (letter, "XYZ"[axis], coord),
                         letter=letter)
            sp.side = cands[0][1] if cands else "below"
            sp.skip = True
            sp.why = "no attach edge for datum plane"
            specs.append(sp)

    # --- position FCF per hole (ASME Y14.5 section 10): primary datum = the
    # plane perpendicular to the hole axis (controls squareness of the axis;
    # the face the hole is machined into), remaining datums by DRF precedence
    for h in holes:
        vname = HOLE_VIEW[h["axis"]]
        prim = datum_axis_letter.get(h["axis"])
        if prim not in datum_ok:
            prim = "A" if "A" in datum_ok else None
        rest = [l for l in ("A", "B", "C") if l != prim and l in datum_ok]
        datums = ([prim] if prim else []) + rest
        sp = DimSpec("fcf", vname, h["axis"],
                     "position dia %s |%s (dia %.5g hole)"
                     % (tolset["pos"], "|".join(datums), 2 * h["r"]),
                     hole=h, tolval=tolset["pos"], datums=datums,
                     characteristic="Position", skip=not datums)
        if sp.skip:
            sp.why = "no datums available"
        sp.side = "callout"
        specs.append(sp)

    # --- DRF qualification (ASME Y14.5: datum features need their own
    # controls so the DRF is realizable): form (flatness) on the primary
    # datum face; orientation (perpendicularity |A, then |A|B) on secondary
    # and tertiary — each frame stacked with its datum feature symbol
    QUAL = {"A": ("Flatness", []),
            "B": ("Perpendicularity", ["A"]),
            "C": ("Perpendicularity", ["A", "B"])}
    for letter in ("A", "B", "C"):
        if letter not in datum_ok:
            continue
        char, refs = QUAL[letter]
        refs = [r for r in refs if r in datum_ok]
        asp = next(s2 for s2 in specs
                   if s2.kind == "datum" and getattr(s2, "letter", "") == letter)
        sp = DimSpec("fcf_qual", asp.view_name, asp.axis,
                     "%s %s%s (datum %s qual)"
                     % (char.lower(), tolset["flat"],
                        (" |" + "|".join(refs)) if refs else "", letter),
                     tolval=tolset["flat"], characteristic=char,
                     datums=refs, under=letter, skip=False)
        sp.side = asp.side
        sp.span = 2e9        # row beyond the datum symbol (stacked frame)
        specs.append(sp)

    # Every feature's location is dimensioned individually — two different
    # holes sharing a coordinate still each get a location dim (ASME Y14.5:
    # each feature of size must be fully located from the DRF; consolidating
    # would require a shared-centerline or pattern callout, not omission).

    # assign rows per (view, side), longest span outermost
    by_side = {}
    for sp in specs:
        if sp.kind in ("linear", "pos", "datum") and not sp.skip:
            by_side.setdefault((sp.view_name, sp.side), []).append(sp)
    for (_, _), lst in by_side.items():
        for i, sp in enumerate(sorted(lst, key=lambda t: t.span)):
            sp.row = i
    return specs


# ------------------------------------------------------------------ 3. field
def detect_field(wp, sheet, template):
    L, H = sheet.Length, sheet.Height
    longs_v, longs_h, small = [], [], []
    for c in wp.Curves:
        try:
            if isinstance(c, NXOpen.Line):
                a, b = c.StartPoint, c.EndPoint
                r = Rect(a.X, a.Y, b.X, b.Y)
                if abs(a.X - b.X) < 0.01 and (r.y1 - r.y0) > 0.6 * H:
                    longs_v.append(a.X)
                elif abs(a.Y - b.Y) < 0.01 and (r.x1 - r.x0) > 0.6 * L:
                    longs_h.append(a.Y)
                else:
                    small.append(r)
            elif isinstance(c, NXOpen.Arc):
                p, r0 = c.CenterPoint, c.Radius
                small.append(Rect(p.X - r0, p.Y - r0, p.X + r0, p.Y + r0))
        except Exception:
            pass
    pad_note_w, pad_note_h = 0.05 * L, 0.015 * H
    for coll in ("Notes", "Labels"):
        for n in getattr(wp, coll, []):
            try:
                o = n.AnnotationOrigin
                small.append(Rect(o.X - pad_note_w, o.Y - pad_note_h,
                                  o.X + pad_note_w, o.Y + pad_note_h))
            except Exception:
                pass
    lefts = [x for x in longs_v if x < L / 2]
    rights = [x for x in longs_v if x >= L / 2]
    bots = [y for y in longs_h if y < H / 2]
    tops = [y for y in longs_h if y >= H / 2]
    m = 0.008 * L
    field = Rect(max(lefts) + m if lefts else 0.05 * L,
                 max(bots) + m if bots else 0.05 * H,
                 min(rights) - m if rights else 0.95 * L,
                 min(tops) - m if tops else 0.95 * H)
    # merge small rects into obstacle clusters
    obstacles = []
    for r in small:
        merged = False
        for i, o in enumerate(obstacles):
            if r.overlaps(o, pad=0.01 * L):
                obstacles[i] = o.union(r)
                merged = True
                break
        if not merged:
            obstacles.append(r)
    changed = True
    while changed:
        changed = False
        for i in range(len(obstacles)):
            for j in range(i + 1, len(obstacles)):
                if obstacles[i].overlaps(obstacles[j], pad=0.01 * L):
                    obstacles[i] = obstacles[i].union(obstacles[j])
                    del obstacles[j]
                    changed = True
                    break
            if changed:
                break
    # keep only obstacles whose center is inside the field (zone labels and
    # border ticks live just outside and must not shadow the drawing area)
    obstacles = [o for o in obstacles
                 if field.x0 <= (o.x0 + o.x1) / 2 <= field.x1
                 and field.y0 <= (o.y0 + o.y1) / 2 <= field.y1]
    # template keep-outs (title block, projection symbol) are authoritative
    obstacles += [Rect(*k) for k in TEMPLATE_KEEPOUTS.get(template, [])]
    say("Field: %r, %d obstacles" % (field, len(obstacles)))
    return field, obstacles


# ----------------------------------------------------------------- 4. layout
def reserves(specs, P):
    """(view_name, side) -> band width needed for stacked dims, paper units.
    Spacing per ASME Y14.5-2009 para 1.7.1: first dimension line >= 10mm from
    the view, successive rows >= 6mm apart (we use 12/8). Qualification frames
    stacked under datum symbols get extra depth (frame box height)."""
    res = {}
    for sp in specs:
        # qual frames sit laterally beside their datum symbol (one combined
        # annotation per Y14.5), so they add no band row of their own
        if sp.kind in ("linear", "pos", "datum") and not sp.skip:
            k = (sp.view_name, sp.side)
            res[k] = max(res.get(k, 0.0), (12.0 + 10.0 * sp.row + 8.0) * P)
    return res


def solve_layout(geom, specs, field, obstacles, u, P):
    dx, dy, dz = geom.ext
    res = reserves(specs, P)

    def R(v, sd):
        return res.get((v, sd), 6.0 * P)

    gap = 24.0 * P

    def bottom_lift(xr0, xr1):
        """Raise the base line above bottom-strip obstacles under this x-range
        (title block, symbols). Obstacles higher up are handled by the
        collision check after placement, not by lifting the whole layout."""
        y = field.y0
        strip = field.y0 + 0.30 * (field.y1 - field.y0)
        for o in obstacles:
            if o.y0 <= strip and o.x1 > xr0 and o.x0 < xr1:
                y = max(y, o.y1 + 3.0 * P)
        return y

    # views that carry diameter callouts (and FCFs) need headroom above:
    # dia text row + feature control frame row
    cal_views = set(sp.view_name for sp in specs
                    if sp.kind in ("dia", "fcf") and not sp.skip)

    def cal(v):
        return 36.0 * P if v in cal_views else 0.0

    def try_scale(num, den):
        sc = float(num) / den * u
        fw, fh = dx * sc, dz * sc
        tw, th = dx * sc, dy * sc
        rw, rh = dy * sc, dz * sc
        x_f = field.x0 + R("Front", "left") + fw / 2
        x_r = x_f + fw / 2 + max(gap, R("Front", "right") + R("Right", "left") + 4 * P) + rw / 2
        # lift each column clear of obstacles beneath it — use real reserves
        # only (default padding must not trigger a lift over the title block)
        f_x0 = x_f - fw / 2 - res.get(("Front", "left"), 0.0)
        f_x1 = x_f + fw / 2 + res.get(("Front", "right"), 0.0)
        r_x0 = x_r - rw / 2 - res.get(("Right", "left"), 0.0)
        r_x1 = x_r + rw / 2 + res.get(("Right", "right"), 0.0)
        base = max(bottom_lift(f_x0, f_x1), bottom_lift(r_x0, r_x1))
        y_f = base + max(R("Front", "below"), R("Right", "below")) + fh / 2
        # gap above Front must hold Front's above band + callout row + Top's below band
        y_t = y_f + fh / 2 + max(gap, R("Front", "above") + cal("Front")
                                 + R("Top", "below") + 4 * P) + th / 2
        need_r = x_r + rw / 2 + R("Right", "right")
        need_t = y_t + th / 2 + R("Top", "above") + cal("Top")
        need_rv = y_f + rh / 2 + R("Right", "above") + cal("Right")
        if need_r > field.x1 or need_t > field.y1 or need_rv > field.y1:
            say("  scale %d:%d rejected: w %.0f/%.0f, topcol %.0f/%.0f, rightcol %.0f/%.0f"
                % (num, den, need_r, field.x1, need_t, field.y1, need_rv, field.y1))
            return None
        return {"sc": sc, "fw": fw, "fh": fh, "tw": tw, "th": th,
                "rw": rw, "rh": rh, "x_f": x_f, "y_f": y_f,
                "x_t": x_f, "y_t": y_t, "x_r": x_r, "y_r": y_f}

    sol = None
    for num, den in STD_SCALES:
        sol = try_scale(num, den)
        if sol:
            break
    if sol is None:
        num, den = STD_SCALES[-1]
        sol = try_scale(num, den)
        rep("WARNING: part does not fit sheet even at %d:%d" % (num, den))
    say("Scale %d:%d" % (num, den))
    sc = sol["sc"]
    fw, fh, tw, th, rw, rh = (sol[k] for k in ("fw", "fh", "tw", "th", "rw", "rh"))
    x_f, y_f, x_t, y_t, x_r, y_r = (sol[k] for k in ("x_f", "y_f", "x_t", "y_t", "x_r", "y_r"))

    def build_vrects(dx_s, dy_s):
        return {
            "Front": Rect(x_f + dx_s - fw / 2, y_f + dy_s - fh / 2,
                          x_f + dx_s + fw / 2, y_f + dy_s + fh / 2),
            "Top": Rect(x_t + dx_s - tw / 2, y_t + dy_s - th / 2,
                        x_t + dx_s + tw / 2, y_t + dy_s + th / 2),
            "Right": Rect(x_r + dx_s - rw / 2, y_r + dy_s - rh / 2,
                          x_r + dx_s + rw / 2, y_r + dy_s + rh / 2),
        }

    def expanded(name, r):
        return Rect(r.x0 - R(name, "left"), r.y0 - R(name, "below"),
                    r.x1 + R(name, "right"), r.y1 + R(name, "above"))

    def collides(vr):
        for n, r in vr.items():
            er = expanded(n, r)
            if er.x0 < field.x0 or er.y0 < field.y0 or \
               er.x1 > field.x1 or er.y1 > field.y1:
                return True
            if any(er.overlaps(o, pad=2 * P) for o in obstacles):
                return True
        return False

    # center the arrangement in the unused field (keep room for iso on right)
    vr0 = build_vrects(0, 0)
    arr = None
    for n, r in vr0.items():
        er = expanded(n, r)
        arr = er if arr is None else arr.union(er)
    iso_w = max(dx, dy, dz) * sc * 1.45 + 16 * P
    free_x = max(0.0, (field.x1 - iso_w) - arr.x1)
    free_y = max(0.0, field.y1 - arr.y1)
    shift = (0.0, 0.0)
    for fx, fy in ((0.5, 0.5), (0.5, 0.25), (0.25, 0.25), (0.25, 0.0), (0.0, 0.0)):
        cand = (free_x * fx, free_y * fy)
        if not collides(build_vrects(*cand)):
            shift = cand
            break
    x_f += shift[0]; x_t += shift[0]; x_r += shift[0]
    y_f += shift[1]; y_t += shift[1]; y_r += shift[1]
    vrects = build_vrects(0, 0) if shift == (0, 0) else {
        n: Rect(r.x0 + shift[0], r.y0 + shift[1], r.x1 + shift[0], r.y1 + shift[1])
        for n, r in vr0.items()}
    occupied = [expanded(n, r) for n, r in vrects.items()] + list(obstacles)

    # isometric: try candidate spots, shrink if needed
    iso_d = max(dx, dy, dz) * sc * 1.45
    placed = None
    for shrink in (1.0, 0.75, 0.5):
        d = iso_d * shrink
        cands = [(field.x1 - d / 2 - 4 * P, field.y1 - d / 2 - 4 * P),
                 (field.x1 - d / 2 - 4 * P, field.y0 + d / 2 + 4 * P),
                 (field.x1 - d / 2 - 4 * P, (field.y0 + field.y1) / 2)]
        for cx, cy in cands:
            r = Rect(cx - d / 2, cy - d / 2, cx + d / 2, cy + d / 2)
            if r.x0 >= field.x0 and r.y0 >= field.y0 and \
               not any(r.overlaps(o, pad=4 * P) for o in occupied):
                placed = (cx, cy, shrink)
                break
        if placed:
            break
    if not placed:
        placed = (field.x1 - iso_d * 0.5 / 2 - 4 * P, field.y1 - iso_d * 0.5 / 2 - 4 * P, 0.5)
        rep("WARNING: isometric may be tight; placed top-right at half scale")
    say("Iso at (%.0f, %.0f) shrink %.2f" % placed)

    return {"num": num, "den": den, "sc": sc, "views": {
        "Front": (x_f, y_f), "Top": (x_t, y_t), "Right": (x_r, y_r)},
        "vrects": vrects, "iso": placed, "res": R, "field": field,
        "obstacles": obstacles}


# ----------------------------------------------------------------- 5. render
def main():
    for f in (DWG, PDF, REPORT):
        if os.path.exists(f):
            os.remove(f)

    mpart, _ = s.Parts.OpenDisplay(MODEL)
    metric = mpart.PartUnits == NXOpen.BasePart.Units.Millimeters
    rep("Model: %s (%s)" % (mpart.Leaf, "mm" if metric else "inch"))

    if metric:
        template, pres, units = ("Drawing-A3-Size-template.prt", "A3 - Size",
                                 NXOpen.Part.Units.Millimeters)
    else:
        template, pres, units = ("Drawing-B-Size-template.prt", "B - Size",
                                 NXOpen.Part.Units.Inches)
    fn = s.Parts.FileNew()
    fn.TemplateFileName = template
    fn.UseBlankTemplate = False
    fn.ApplicationName = "DrawingTemplate"
    fn.Units = units
    fn.TemplateType = NXOpen.FileNewTemplateType.Item
    fn.TemplatePresentationName = pres
    fn.UsesMasterModel = "Yes"
    fn.MasterFileName = MODEL
    fn.NewFileName = DWG
    fn.MakeDisplayedPart = True
    fn.Commit()
    fn.Destroy()
    wp = s.Parts.Work

    master = None
    for p in s.Parts:
        if os.path.normcase(p.FullPath) == os.path.normcase(MODEL):
            master = p
    if master is None:
        raise RuntimeError("master model not loaded")

    # refset + hide template datums
    try:
        names = [r.Name for r in master.GetAllReferenceSets()]
        target = next((n for n in names if n.upper() in ("MODEL", "SOLID", "BODY")), None)
        if target:
            for comp in wp.ComponentAssembly.RootComponent.GetChildren():
                wp.ComponentAssembly.ReplaceReferenceSet(comp, target)
    except Exception:
        pass
    try:
        blank = []
        for cn in ("Datums", "Points", "CoordinateSystems"):
            coll = getattr(wp, cn, None)
            if coll is not None:
                blank.extend(list(coll))
        if blank:
            s.DisplayManager.BlankObjects(blank)
    except Exception:
        pass

    # 1-2: analyze + plan
    geom = Geometry(master)
    holes = group_holes(geom)
    rep("Geometry: extent %.5g x %.5g x %.5g; levels X:%d Y:%d Z:%d; %d hole feature(s)"
        % (tuple(geom.ext) + tuple(len(l) for l in geom.levels) + (len(holes),)))
    if getattr(geom, "n_circ_fail", 0):
        rep("NOTE: %d of %d circular edges could not be fitted (non-axis-aligned?)"
            % (geom.n_circ_fail, geom.n_circ))
    if os.environ.get("NXDRAW_DEBUG"):
        for axis, coord, area in sorted(geom.planar_faces, key=lambda t: -t[2])[:10]:
            say("  face: %s=%.5g area %.6g" % ("XYZ"[axis], coord, area))
    specs = plan_dimensions(geom, holes, metric)

    w_mm = wp.PartUnits == NXOpen.BasePart.Units.Millimeters
    u = 1.0 if metric == w_mm else (1 / 25.4 if metric else 25.4)
    P = 1.0 if w_mm else 1 / 25.4       # paper unit (annotation mm) in drawing units

    sheet = wp.DrawingSheets.CurrentDrawingSheet
    field, obstacles = detect_field(wp, sheet, template)

    # reserve space for the general tolerance note above the title block
    kos = TEMPLATE_KEEPOUTS.get(template, [])
    note_rect = None
    if kos:
        tb = max((Rect(*k) for k in kos),
                 key=lambda r: (r.x1 - r.x0) * (r.y1 - r.y0))
        note_rect = Rect(tb.x0, tb.y1 + 2 * P, tb.x0 + 100 * P, tb.y1 + 26 * P)
        obstacles.append(note_rect)

    # 3-4: layout
    lay = solve_layout(geom, specs, field, obstacles, u, P)
    num, den, sc = lay["num"], lay["den"], lay["sc"]

    dsb = wp.DrawingSheets.DrawingSheetBuilder(sheet)
    try:
        dsb.Option = NXOpen.Drawings.DrawingSheetBuilder.SheetOption.StandardSize
        dsb.ProjectionAngle = NXOpen.Drawings.DrawingSheetBuilder.SheetProjectionAngle.Third
        dsb.Height, dsb.Length = sheet.Height, sheet.Length
        want = "S%d%d" % (num, den)
        if metric:
            dsb.Units = NXOpen.Drawings.DrawingSheetBuilder.SheetUnits.Metric
            et = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardMetricScale
            dsb.StandardMetricScale = getattr(et, want) if hasattr(et, want) else et.Custom
        else:
            dsb.Units = NXOpen.Drawings.DrawingSheetBuilder.SheetUnits.English
            et = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardEnglishScale
            dsb.StandardEnglishScale = getattr(et, want) if hasattr(et, want) else et.Custom
        if not hasattr(et, want):
            dsb.ScaleNumerator, dsb.ScaleDenominator = float(num), float(den)
        dsb.Number = "1"
        dsb.Commit()
    finally:
        dsb.Destroy()
    sheet = wp.DrawingSheets.CurrentDrawingSheet

    views = {}

    def add_view(model_view, x, y, vnum, vden, dashed=True, key=None):
        bvb = wp.DraftingViews.CreateBaseViewBuilder(NXOpen.Drawings.BaseView.Null)
        try:
            bvb.SelectModelView.SelectedView = wp.ModelingViews.FindObject(model_view)
            bvb.Scale.Numerator = float(vnum)
            bvb.Scale.Denominator = float(vden)
            if dashed:
                # hidden lines dashed in orthographic views (ASME Y14.2 line
                # conventions); pictorial views omit them for clarity (Y14.3)
                hl = bvb.Style.ViewStyleHiddenLines
                if isinstance(hl.HiddenLine, bool):
                    hl.HiddenLine = True
                hl.Font = NXOpen.Preferences.Font.Dashed
            bvb.Placement.Placement.SetValue(None, None, NXOpen.Point3d(x, y, 0.0))
            views[key or model_view] = bvb.Commit()
            say("View %s at (%.1f, %.1f)" % (model_view, x, y))
        finally:
            bvb.Destroy()

    for name in ("Front", "Top", "Right"):
        x, y = lay["views"][name]
        add_view(name, x, y, num, den)
    ix, iy, shrink = lay["iso"]
    inum, iden = num, den
    if shrink < 1.0:
        inum, iden = num, den * (2 if shrink <= 0.5 else 1)
        if shrink == 0.75:
            inum, iden = num * 3, den * 4
    add_view("Trimetric", ix, iy, inum, iden, dashed=False, key="Iso")

    # 5: dimensions
    comp0 = wp.ComponentAssembly.RootComponent.GetChildren()[0]

    def occ(obj):
        try:
            o = comp0.FindOccurrence(obj)
            return o if o is not None else obj
        except Exception:
            return obj

    am = wp.Annotations
    po = NXOpen.Annotations.AssociativityPointOption

    def assoc(obj, view, pt, opt):
        a = am.NewAssociativity()
        a.FirstObject = occ(obj)
        a.ObjectView = view
        a.PickPoint = pt
        a.PointOption = opt
        return a

    def model_to_sheet(vname, pt3):
        """Model point -> sheet coords in the given principal view."""
        h_ax, v_ax, _ = VIEWDEF[vname]
        cx, cy = lay["views"][vname]
        mid = [(geom.lo[i] + geom.hi[i]) / 2 for i in range(3)]
        p = (pt3[0], pt3[1], pt3[2])
        return (cx + (p[h_ax] - mid[h_ax]) * sc, cy + (p[v_ax] - mid[v_ax]) * sc)

    def dim_origin(sp, pa=None, pb=None):
        """Text origin: dim band offset on the side axis, mid-span of the
        measured points along the other axis (text sits between its arrows)."""
        vr = lay["vrects"][sp.view_name]
        off = (12.0 + 10.0 * sp.row) * P
        mid_x = (vr.x0 + vr.x1) / 2
        mid_y = (vr.y0 + vr.y1) / 2
        if pa is not None and pb is not None:
            sa = model_to_sheet(sp.view_name, pa)
            sb = model_to_sheet(sp.view_name, pb)
            mid_x = (sa[0] + sb[0]) / 2
            mid_y = (sa[1] + sb[1]) / 2
        if sp.side == "below":
            return (mid_x, vr.y0 - off)
        if sp.side == "above":
            return (mid_x, vr.y1 + off)
        if sp.side == "left":
            return (vr.x0 - off, mid_y)
        return (vr.x1 + off, mid_y)

    def set_unidirectional(dim):
        """ASME Y14.5 unidirectional system: all dimension text reads
        horizontally from the bottom of the sheet (no leader-aligned or
        rotated text)."""
        try:
            dp = dim.GetDimensionPreferences()
            dp.TextOrientation = NXOpen.Annotations.TextOrientation.Horizontal
            dim.SetDimensionPreferences(dp)
        except Exception:
            pass

    def narrow_origin(sp, ox, oy, pa, pb):
        """Arrows + text cannot fit between close extension lines (~18mm on
        paper): move the text outside the span along the dimension line
        (ASME narrow-dimension practice), dodging other text in the band."""
        if sp.span * sc >= 18 * P:
            return ox, oy
        sa = model_to_sheet(sp.view_name, pa)
        sb = model_to_sheet(sp.view_name, pb)
        placed = text_pos.get((sp.view_name, sp.side), [])
        if sp.horizontal:
            ox = max(sa[0], sb[0]) + 9 * P
            guard = 0
            while guard < 12 and any(abs(ox - t) < 8 * P for t in placed):
                ox += 8 * P
                guard += 1
        else:
            oy = max(sa[1], sb[1]) + 9 * P
            guard = 0
            while guard < 12 and any(abs(oy - t) < 8 * P for t in placed):
                oy += 8 * P
                guard += 1
        return ox, oy

    made = 0
    callout_x = {}      # view_name -> placed callout x positions
    datum_origins = {}  # letter -> sheet origin of the datum symbol
    text_pos = {}       # (view, side) -> along-axis coords of placed dim text
    for sp in specs:
        if getattr(sp, "skip", True):
            continue
        view = views[sp.view_name]
        try:
            if sp.kind == "linear":
                e0, p0, e1, p1 = sp.geo
                dd = am.NewDimensionData()
                dd.SetAssociativity(1, [assoc(e0, view, p0, po.OnCurve)])
                dd.SetAssociativity(2, [assoc(e1, view, p1, po.OnCurve)])
                ox, oy = dim_origin(sp, (p0.X, p0.Y, p0.Z), (p1.X, p1.Y, p1.Z))
                ox, oy = narrow_origin(sp, ox, oy,
                                       (p0.X, p0.Y, p0.Z), (p1.X, p1.Y, p1.Z))
                text_pos.setdefault((sp.view_name, sp.side), []).append(
                    ox if sp.side in ("below", "above") else oy)
                opt = NXOpen.Point3d(ox, oy, 0.0)
                if sp.horizontal:
                    d = wp.Dimensions.CreateHorizontalDimension(dd, opt)
                else:
                    d = wp.Dimensions.CreateVerticalDimension(dd, opt)
                set_unidirectional(d)
            elif sp.kind == "pos":
                h = sp.hole
                e0, p0 = sp.geo
                cpt = NXOpen.Point3d(*h["center"])
                dd = am.NewDimensionData()
                dd.SetAssociativity(1, [assoc(e0, view, p0, po.OnCurve)])
                dd.SetAssociativity(2, [assoc(h["edge"], view, cpt, po.ArcCenter)])
                ox, oy = dim_origin(sp, (p0.X, p0.Y, p0.Z), h["center"])
                ox, oy = narrow_origin(sp, ox, oy,
                                       (p0.X, p0.Y, p0.Z), h["center"])
                text_pos.setdefault((sp.view_name, sp.side), []).append(
                    ox if sp.side in ("below", "above") else oy)
                opt = NXOpen.Point3d(ox, oy, 0.0)
                if sp.horizontal:
                    d = wp.Dimensions.CreateHorizontalDimension(dd, opt)
                else:
                    d = wp.Dimensions.CreateVerticalDimension(dd, opt)
                # locations controlled by position tolerances are BASIC dims
                # (ASME Y14.5 para 8.4 — untoleranced theoretically exact)
                try:
                    tt = getattr(NXOpen.Annotations, "ToleranceType", None)
                    if tt is not None and hasattr(tt, "Basic"):
                        d.ToleranceType = tt.Basic
                except Exception:
                    sp.why = "placed, but basic style not applied"
                set_unidirectional(d)
            elif sp.kind == "dia":
                h = sp.hole
                h_ax, v_ax, _ = VIEWDEF[sp.view_name]
                vr = lay["vrects"][sp.view_name]
                band = lay["res"](sp.view_name, "above")
                hx = model_to_sheet(sp.view_name, h["center"])[0]
                # text offset to the right of the hole's own extension line;
                # dodge other holes' extension lines and other callouts
                sx = hx + 16 * P
                ext_xs = [model_to_sheet(sp.view_name, h2["center"])[0]
                          for h2 in holes if HOLE_VIEW[h2["axis"]] == sp.view_name]
                # spacing must clear a whole neighbor group (frame ~44 wide)
                # plus this callout's leader corridor, so the leader cannot
                # pass through a neighbor's tolerance frame
                used = callout_x.setdefault(sp.view_name, [])
                guard = 0
                while guard < 40 and (
                        any(abs(sx - x0) < 58 * P for x0 in used)
                        or any(abs(sx - x0) < 8 * P for x0 in ext_xs)):
                    sx += 10 * P
                    guard += 1
                used.append(sx)
                # attach on the circle quadrant facing the callout
                dxs = 1.0 if sx >= hx else -1.0
                pk = list(h["center"])
                pk[h_ax] += dxs * h["r"] * 0.7071
                pk[v_ax] += h["r"] * 0.7071
                rdb = wp.Dimensions.CreateRadialDimensionBuilder(None)
                try:
                    try:
                        rdb.IsHoleStyle = True
                    except Exception:
                        pass
                    rdb.FirstAssociativity.SetValue(occ(h["edge"]), view,
                                                    NXOpen.Point3d(*pk))
                    # hole extent on the callout (ASME Y14.5 hole callouts:
                    # depth for blind holes, THRU when it pierces the part;
                    # words used in lieu of the depth symbol, per pre-1994
                    # practice, still unambiguous)
                    try:
                        note = "THRU" if h["through"] else (
                            "%.5g DEEP" % h["span"] if h["span"] > 0 else None)
                        if note:
                            atb = rdb.AppendedText
                            for setter in ("SetBelow", "SetAfter"):
                                if hasattr(atb, setter):
                                    getattr(atb, setter)([note])
                                    break
                    except Exception:
                        say("  callout note failed:\n"
                            + traceback.format_exc().splitlines()[-1])
                    oy = vr.y1 + band + 24 * P
                    h["callout_origin"] = (sx, oy)
                    rdb.Origin.Origin.SetValue(None, None, NXOpen.Point3d(sx, oy, 0.0))
                    h["dim_obj"] = rdb.Commit()
                    set_unidirectional(h["dim_obj"])
                finally:
                    rdb.Destroy()
            elif sp.kind == "datum":
                e, pt = sp.geo
                vs = e.GetVertices()
                a2, b2 = vs[0], vs[1]
                placed = text_pos.get((sp.view_name, sp.side), [])
                if placed:
                    # band shared with dims: attach near the edge end at the
                    # low corner — the leader then approaches outside the dim
                    # lines' span (Y14.5: leaders must not cross dim lines;
                    # crossing extension line ends is permitted)
                    sa = model_to_sheet(sp.view_name, (a2.X, a2.Y, a2.Z))
                    sb = model_to_sheet(sp.view_name, (b2.X, b2.Y, b2.Z))
                    ci = 1 if sp.side in ("left", "right") else 0
                    frac = 0.10 if sa[ci] <= sb[ci] else 0.90
                    best_att = (a2.X + frac * (b2.X - a2.X),
                                a2.Y + frac * (b2.Y - a2.Y),
                                a2.Z + frac * (b2.Z - a2.Z))
                else:
                    # empty band: attach where farthest from any dim text
                    best_att, best_d = None, -1.0
                    for frac in (0.85, 0.15, 0.65, 0.35, 0.5):
                        cand = (a2.X + frac * (b2.X - a2.X),
                                a2.Y + frac * (b2.Y - a2.Y),
                                a2.Z + frac * (b2.Z - a2.Z))
                        sxy = model_to_sheet(sp.view_name, cand)
                        coord = sxy[0] if sp.side in ("below", "above") else sxy[1]
                        d = min((abs(coord - t) for t in placed), default=1e9)
                        if d > best_d:
                            best_d, best_att = d, cand
                att = NXOpen.Point3d(*best_att)
                sp.att = att
                dsb = am.Datums.CreateDraftingDatumFeatureSymbolBuilder(
                    NXOpen.Annotations.Datum.Null)
                try:
                    dsb.Letter = sp.letter
                    ld = am.CreateLeaderData()
                    ld.Leader.SetValue(occ(e), view, att)
                    dsb.Leader.Leaders.Append(ld)
                    ox, oy = dim_origin(sp, (att.X, att.Y, att.Z), (att.X, att.Y, att.Z))
                    # extra clearance beyond the dim rows on this band
                    if sp.side == "below":
                        oy -= 5 * P
                    elif sp.side == "above":
                        oy += 5 * P
                    elif sp.side == "left":
                        ox -= 5 * P
                    else:
                        ox += 5 * P
                    # band shared with dims: escape past the low view corner
                    # (matches the end-attach above; leader clears dim lines)
                    if placed:
                        vr2 = lay["vrects"][sp.view_name]
                        if sp.side in ("left", "right"):
                            oy = vr2.y0 - 10 * P
                        else:
                            ox = vr2.x0 - 10 * P
                    fld = lay["field"]
                    ox = min(max(ox, fld.x0 + 16 * P), fld.x1 - 16 * P)
                    oy = min(max(oy, fld.y0 + 8 * P), fld.y1 - 8 * P)
                    dsb.Origin.Origin.SetValue(None, None, NXOpen.Point3d(ox, oy, 0.0))
                    dsb.Commit()
                    datum_origins[sp.letter] = (ox, oy)
                finally:
                    dsb.Destroy()
            elif sp.kind in ("fcf", "fcf_qual"):
                ech = NXOpen.Annotations.FeatureControlFrameBuilder.FcfCharacteristic
                fcf = am.CreateDraftingFeatureControlFrameBuilder(
                    NXOpen.Annotations.Gdt.Null)
                try:
                    fcf.Characteristic = getattr(ech, sp.characteristic)
                    fd = fcf.FeatureControlFrameDataList.FindItem(0)
                    fd.ToleranceValue = sp.tolval
                    # datum references (position: |prim|sec|tert;
                    # perpendicularity: |A or |A|B; flatness: none)
                    refs = (fd.PrimaryDatumReference,
                            fd.SecondaryDatumReference,
                            fd.TertiaryDatumReference if
                            hasattr(fd, "TertiaryDatumReference") else None)
                    for ref, letter in zip(refs, sp.datums):
                        if ref is None:
                            break
                        if hasattr(ref, "Letter"):
                            ref.Letter = letter
                        else:
                            dump("DatumReferenceBuilder", ref)
                            raise RuntimeError("no Letter on datum ref")
                    if sp.kind == "fcf":
                        # diameter zone symbol for position tolerance
                        for a in dir(fd):
                            if "zoneshape" in a.lower() or a == "ZoneShape":
                                try:
                                    zt = type(getattr(fd, a))
                                    for m in dir(zt):
                                        if "diameter" in m.lower():
                                            setattr(fd, a, getattr(zt, m))
                                            break
                                except Exception:
                                    pass
                                break
                        # leaderless frame docked directly under the diameter
                        # callout text — reads as one group per Y14.5, and a
                        # second leader to the hole would cross dims/views
                        h = sp.hole
                        cx0, cy0 = h.get("callout_origin", (None, None))
                        vr = lay["vrects"][sp.view_name]
                        if cx0 is None:
                            cx0, cy0 = vr.x1 + 20 * P, vr.y1 + 10 * P
                        # below the two-line callout text (size + THRU/DEEP),
                        # shifted right so the leader stub clears the frame
                        fcf.Origin.Origin.SetValue(
                            None, None, NXOpen.Point3d(cx0 + 4 * P, cy0 - 16 * P, 0.0))
                    else:
                        # qualification frame stacked directly under its datum
                        # symbol, leader to the same attach point (one group)
                        asp = next(s2 for s2 in specs
                                   if s2.kind == "datum"
                                   and getattr(s2, "letter", "") == sp.under)
                        e, pt = asp.geo
                        pt = getattr(asp, "att", pt)
                        ax0, ay0 = datum_origins.get(sp.under, (None, None))
                        vr = lay["vrects"][sp.view_name]
                        if ax0 is None:
                            ax0, ay0 = (vr.x0 + vr.x1) / 2, vr.y0 - 24 * P
                        # frame beside/below the datum box (combined group,
                        # no extra band row); dodges obstacles and the
                        # adjacent band's dimension rows
                        fld = lay["field"]
                        vr = lay["vrects"][sp.view_name]
                        if asp.side in ("below", "above"):
                            cands = [(ax0 + 15 * P, ay0), (ax0 - 42 * P, ay0),
                                     (ax0, ay0 - 12 * P)]
                        else:
                            bel = lay["res"](sp.view_name, "below")
                            qy_deep = min(ay0, vr.y0 - bel) - 12 * P
                            if text_pos.get((asp.view_name, asp.side)):
                                # corner-escaped datum sits near the below
                                # band: drop the frame beneath those rows
                                cands = [(ax0, qy_deep), (ax0 - 42 * P, qy_deep)]
                            else:
                                cands = [(ax0, ay0 - 12 * P), (ax0, qy_deep)]
                        qx, qy = cands[-1]
                        for cx2, cy2 in cands:
                            r2 = Rect(cx2 - 2 * P, cy2 - 5 * P,
                                      cx2 + 28 * P, cy2 + 5 * P)
                            if r2.x0 < fld.x0 or r2.x1 > fld.x1 or r2.y0 < fld.y0:
                                continue
                            if any(r2.overlaps(o, pad=1.5 * P)
                                   for o in lay["obstacles"]):
                                continue
                            if any(r2.overlaps(v2, pad=1.5 * P)
                                   for v2 in lay["vrects"].values()):
                                continue
                            qx, qy = cx2, cy2
                            break
                        # adjacent to its datum symbol: adjacency conveys the
                        # association, and a second leader to the same attach
                        # point would cross the datum box (leaders must not
                        # cross annotation per Y14.5 practice)
                        adjacent = abs(qx - ax0) <= 20 * P and abs(qy - ay0) <= 16 * P
                        if not adjacent:
                            # attach diverged along the edge from the datum's
                            # own attach so this leader clears the datum box
                            att2 = pt
                            try:
                                vs2 = e.GetVertices()
                                a3, b3 = vs2[0], vs2[1]
                                dx3 = b3.X - a3.X
                                dy3 = b3.Y - a3.Y
                                dz3 = b3.Z - a3.Z
                                ln2 = dx3 * dx3 + dy3 * dy3 + dz3 * dz3
                                t0 = ((pt.X - a3.X) * dx3 + (pt.Y - a3.Y) * dy3
                                      + (pt.Z - a3.Z) * dz3) / ln2 if ln2 else 0.5
                                t2 = t0 + 0.22 if t0 < 0.5 else t0 - 0.22
                                att2 = NXOpen.Point3d(a3.X + t2 * dx3,
                                                      a3.Y + t2 * dy3,
                                                      a3.Z + t2 * dz3)
                            except Exception:
                                pass
                            ld = am.CreateLeaderData()
                            ld.Leader.SetValue(occ(e), view, att2)
                            fcf.Leader.Leaders.Append(ld)
                        fcf.Origin.Origin.SetValue(
                            None, None, NXOpen.Point3d(qx, qy, 0.0))
                    fcf.Commit()
                finally:
                    fcf.Destroy()
            sp.ok = True
            made += 1
        except Exception:
            sp.ok = False
            sp.why = traceback.format_exc().splitlines()[-1]

    # general tolerance note above the title block
    if note_rect is not None:
        try:
            nb = am.CreateDraftingNoteBuilder(NXOpen.Annotations.SimpleDraftingAid.Null)
            try:
                nb.Text.TextBlock.SetText(GDT[metric]["note"])
                nb.Origin.Origin.SetValue(
                    None, None,
                    NXOpen.Point3d(note_rect.x0 + 2 * P, note_rect.y1 - 4 * P, 0.0))
                nb.Commit()
                rep("General tolerance note placed")
            finally:
                nb.Destroy()
        except Exception:
            rep("General tolerance note FAILED: "
                + traceback.format_exc().splitlines()[-1])

    # 6: report
    rep("--- dimension coverage ---")
    for sp in specs:
        if sp.kind == "scheme":
            rep("  INFO %s" % sp.label)
        elif getattr(sp, "skip", False):
            rep("  SKIP %-10s %-24s: %s" % (sp.kind, sp.label, sp.why))
        elif sp.ok:
            rep("  OK   %-10s %-24s -> %s/%s" % (sp.kind, sp.label, sp.view_name, sp.side))
        else:
            rep("  FAIL %-10s %-24s: %s" % (sp.kind, sp.label, sp.why))
    n_ok = sum(1 for sp in specs if sp.ok)
    n_all = sum(1 for sp in specs if sp.kind != "scheme")
    rep("Coverage: %d/%d planned dimensions placed" % (n_ok, n_all))

    wp.Save(NXOpen.BasePart.SaveComponents.TrueValue,
            NXOpen.BasePart.CloseAfterSave.FalseValue)
    say("Saved " + DWG)

    pdfb = wp.PlotManager.CreatePrintPdfbuilder()
    try:
        pdfb.Scale = 1.0
        pdfb.Filename = PDF
        pdfb.SourceBuilder.SetSheets([sheet])
        pdfb.Commit()
        say("PDF exported: " + PDF)
    finally:
        pdfb.Destroy()

    with open(REPORT, "w") as f:
        f.write("\n".join(report_lines) + "\n")
    say("Report: " + REPORT)
    say("DONE")


if __name__ == "__main__":
    main()
